Repository Eggmeoni-na/scrumble-FE, pull requests merged in 2025-09, with the labels that each got.

#241 [Feat-238] 투두 조회를 위한 캘린더 개편
  package.json
  pnpm-lock.yaml
  src/Pages/SquadDetailPage.tsx
  src/assets/icons/arrowLeft.svg
  src/assets/icons/arrowRight.svg
  src/assets/icons/daily.svg
  src/assets/icons/index.ts
  src/assets/icons/monthly.svg
  src/assets/icons/weekly.svg
  src/components/Calendar/index.tsx
  src/components/Calendar/style.ts
  src/components/ProgressRate/index.tsx
  src/components/Todo/Container.tsx
  src/components/Todo/List.tsx
  src/stores/progressRete.ts
  src/styles/palette.ts
Labels: 디벨롭, 디자인

#243 Release: 스크럼블 1.1.0 release
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/Pages/SquadDetailPage.tsx
  src/Pages/SquadPage/index.tsx
  src/Pages/SquadPage/style.ts
  src/assets/icons/arrowLeft.svg
  src/assets/icons/arrowRight.svg
  src/assets/icons/daily.svg
  src/assets/icons/emotionSadLine.svg
  src/assets/icons/index.ts
  src/assets/icons/monthly.svg
  src/assets/icons/weekly.svg
  src/components/Calendar/index.tsx
  src/components/Calendar/style.ts
  src/components/Member/MemberProfile.tsx
  src/components/Member/SquadDetailMemberList.tsx
  src/components/ProgressRate/index.tsx
  src/components/Todo/Container.tsx
  src/components/Todo/List.tsx
  src/components/Todo/styles.tsx
  src/components/common/EmptyContent/index.tsx
  src/components/common/EmptyContent/style.ts
  src/components/common/ErrorBoundary/FallbackWrapper.tsx
  src/components/layouts/Container.tsx
  src/components/layouts/Main.tsx
  src/stores/progressRete.ts
  src/styles/palette.ts
  src/styles/theme.ts
  src/types/emotion.d.ts
Labels: 운영 배포

#245 Release: 스크럼블 1.1.1 release
  package.json
  src/Pages/LoginPage.tsx
  src/components/Calendar/style.ts
  src/components/Member/MemberProfile.tsx
  src/components/Todo/styles.tsx
Labels: 운영 배포

#249 [Fix-248] 월별 투두 조회 시 이전/다음 달 텍스트 스타일 우선순위 조정
  .github/workflows/fork-sync.yml
  src/components/Calendar/style.ts
Labels: 디자인
